# Generated by Django 4.2 on 2023-04-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipecard', '0003_recipe_nutrient_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutrient_info',
            field=models.CharField(max_length=255),
        ),
    ]
