# Generated by Django 4.2 on 2023-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipecard', '0002_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrient_info',
            field=models.JSONField(default=list),
        ),
    ]
